affordable_water/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from two_factor.urls import urlpatterns as tf_urls

from .admin import AdminSiteOTPRequiredMixinRedirSetup

admin.site.__class__ = AdminSiteOTPRequiredMixinRedirSetup

handler404 = 'pathways.views.handler404'
handler500 = 'pathways.views.handler500'

urlpatterns = [path('i18n/', include('django.conf.urls.i18n'), name='set_language'),]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('', include('pathways.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='pathways/password_reset.html'), 
        name='password_reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='pathways/password_reset_done.html'), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='pathways/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='pathways/password_reset_complete.html'), 
        name='password_reset_complete'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pathways/urls.py
from django.urls import path

from pathways import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='pathways-home'),
    path('about/', views.AboutView.as_view(),name='pathways-about'),
    path('nondiscrimination/', views.NondiscriminationView.as_view(), name='pathways-nondiscrimination'),
    path('privacy/', views.PrivacyView.as_view(), name='pathways-privacy'),
    path('metrics/', views.ProgramMetricsView.as_view(), name='pathways-metrics'),
    path('apply/', views.ApplyOverviewAssistanceView.as_view(),
        name='pathways-apply'),
    path('apply/discount-overview/', views.ApplyDiscountView.as_view(),
        name='pathways-apply-discount-overview'),
    # Amnesty Debt Forgiveness
    path('forgive/overview/', views.ForgiveOverviewView.as_view(),
        name='pathways-forgive-overview'),
    path('forgive/city-resident/', views.ForgiveCityResidentView.as_view(),
        name='pathways-forgive-city-resident'),
    path('forgive/additional-questions/', views.ForgiveAdditionalQuestionsView.as_view(),
        name='pathways-forgive-additional-questions'),
    path('forgive/resident-info/', views.ForgiveResidentInfoView.as_view(),
        name='pathways-forgive-resident-info'),
    path('forgive/refer/', views.ForgiveReferralView.as_view(),
        name='pathways-forgive-refer'),
    path('forgive/review-application/', views.ForgiveReviewApplicationView.as_view(),
        name='pathways-forgive-review-application'),
    path('forgive/confirmation/', views.ForgiveConfirmationView.as_view(),
        name='pathways-forgive-confirmation'),
    path('apply/city-resident/', views.CityResidentView.as_view(),
        name='pathways-apply-city-resident'),    
    path('apply/non-resident/', views.NonResidentView.as_view(),
        name='pathways-apply-non-resident'),
    # Household
    path('apply/household-size/', views.HouseholdSizeView.as_view(),
        name='pathways-apply-household-size'),
    path('apply/household-benefits/', views.HouseholdBenefitsView.as_view(),
        name='pathways-apply-household-benefits'),
    # Income
    path('apply/household-contributors/', views.HouseholdContributorsView.as_view(),
        name='pathways-apply-household-contributors'),
    path('apply/job-status/', views.JobStatusView.as_view(),
        name='pathways-apply-job-status'),
    path('apply/self-employment/', views.SelfEmploymentView.as_view(),
        name='pathways-apply-self-employment'),
    path('apply/number-of-jobs/', views.NumberOfJobsView.as_view(),
        name='pathways-apply-number-of-jobs'),
    path('apply/income-methods/', views.IncomeMethodsView.as_view(),
        name='pathways-apply-income-methods'),
    path('apply/income/', views.IncomeView.as_view(),
        name='pathways-apply-income'),
    path('apply/other-income-sources/', views.OtherIncomeSourcesView.as_view(),
        name='pathways-apply-other-income-sources'),
    path('apply/non-job-income/', views.NonJobIncomeView.as_view(),
        name='pathways-apply-non-job-income'),
    # Eligibility
    path('apply/review-eligibility/', views.ReviewEligibilityView.as_view(),
        name='pathways-apply-review-eligibility'),
    path('apply/eligibility/', views.EligibilityView.as_view(),
        name='pathways-apply-eligibility'),
    # Additional Info
    path('apply/additional-questions/', views.AdditionalQuestionsView.as_view(),
        name='pathways-apply-additional-questions'),
    path('apply/resident-info/', views.ResidentInfoView.as_view(),
        name='pathways-apply-resident-info'),
    path('apply/account-holder/', views.AccountHolderView.as_view(),
        name='pathways-apply-account-holder'),
    path('apply/address/', views.AddressView.as_view(),
        name='pathways-apply-address'),
    path('apply/contact-info/', views.ContactInfoView.as_view(),
        name='pathways-apply-contact-info'),
    path('apply/account-number/', views.AccountNumberView.as_view(),
        name='pathways-apply-account-number'),
    # Review and sign
    path('apply/review-application/', views.ReviewApplicationView.as_view(),
        name='pathways-apply-review-application'),
    path('apply/legal/', views.LegalView.as_view(),
        name='pathways-apply-legal'),
    path('apply/refer/', views.ReferralView.as_view(),
        name='pathways-apply-refer'),
    path('apply/signature/', views.SignatureView.as_view(),
        name='pathways-apply-signature'),
    # Documents
    path('apply/documents-overview/', views.DocumentOverviewView.as_view(),
        name='pathways-apply-documents-overview'),
    path('apply/documents-income/', views.DocumentIncomeView.as_view(),
        name='pathways-apply-documents-income'),
    path('apply/documents-residence/', views.DocumentResidenceView.as_view(),
        name='pathways-apply-documents-residence'),
    path('apply/confirmation/', views.ConfirmationView.as_view(),
        name='pathways-apply-confirmation'),
    path('later-documents/', views.LaterDocumentsView.as_view(),
        name='pathways-later-documents'),
    path('later-documents/no-match-found/', views.NoDocumentFoundView.as_view(),
        name='pathways-later-documents-not-found'),
    path('later-documents/more-info-needed/', views.MoreDocumentInfoRequiredView.as_view(),
        name='pathways-later-documents-more-info')
]

pathways/models.py
from django.db import models
from django.core.validators import RegexValidator, ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils.deconstruct import deconstructible
from django.template.defaultfilters import filesizeformat
from datetime import datetime
from simple_history.models import HistoricalRecords
import magic

from pathways import helpers

class Application(models.Model):
    # Metadata
    history = HistoricalRecords()

    HOUSEHOLD_SIZE_CHOICES = [
        (1,_('Just me')),
        (2,_('2 people')),
        (3,_('3 people')),
        (4,_('4 people')),
        (5,_('5 people')),
        (6,_('6 people')),
        (7,_('7 people')),
        (8,_('8 people')),
    ]
    # HouseholdForm
    household_size = models.IntegerField(
        choices=HOUSEHOLD_SIZE_CHOICES,
        help_text=_("Typically how many people you regularly share living expenses with, including yourself. "
                    "If you live with them, include children under 21, spouses/partners, and parents.")
    )
    # AutoEligibleForm
    has_household_benefits = models.BooleanField()

    # Data from Income forms will be in a seperate model because 
    # if has_household_benefits is True, user won't have to enter income data
    annual_income = models.DecimalField(
        max_digits=11,
        decimal_places=2,
        blank=True,
        default=0,
        help_text=_("Must specify annual income if applicant does not have other household benefits (HEAP, SNAP, etc.)")
    )

    # ResidentInfoForm
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    middle_initial = models.CharField(max_length=5, blank=True)
    rent_or_own = models.CharField(
        max_length=4, 
        choices=(
            ('rent',_("Rent")),
            ('own',_("Own")))
    )

    # AddressForm
    street_address = models.CharField(
        max_length=200,
        validators=[RegexValidator(
            regex=r'^\d+ .*',
            message=_("Make sure to enter a street number before the street name, for example 123 Main St"))
        ]
    )
    apartment_unit = models.CharField(
        max_length=10,
        blank=True,
        help_text=_("Skip this if you don't live in an apartment")
    )
    zip_code = models.CharField(
        max_length=5,
        validators=[RegexValidator(
            regex=r'^\d{5}$',
            message=_("Your ZIP code must be exactly 5 digits"))
        ]
    )

    # ContactInfoForm
    phone_number = models.CharField(
        max_length=12, 
        validators=[RegexValidator(
            regex=r'^(\d{10}|(\d{3}\-\d{3}\-\d{4}))|(\(\d{3}\)\s?\d{3}\-\d{4})',
            message=_("Please use a valid phone number format such as 716-555-5555."))
            ]
    )
    email_address = models.EmailField(
        blank=True, 
        help_text=_("Optional to provide for status updates on your application")
    )

    # account_holder in ResidentInfoForm
    account_holder = models.CharField(max_length=8, choices=[
        ('me',_("Me")),
        ('landlord',_("My landlord")),
        ('other',_("Another person")),
    ])

    # AccountHolderForm
    account_first = models.CharField(max_length=100)
    account_last = models.CharField(max_length=100)
    account_middle = models.CharField(max_length=5, blank=True)

    # AccountNumberForm
    account_number = models.CharField(
        max_length=30,
        blank=True,
        validators=[RegexValidator(
            regex=r'^\d+$',
            message=_("Please enter only digits"))
        ]
    )

    # LegalForm
    legal_agreement = models.BooleanField()

    # SignatureForm
    signature = models.CharField(max_length=250)

    STATUS_CHOICES = [
        ('new',_("New")),
        ('in_progress', _("In Progress")),
        ('enrolled',_("Enrolled")),
        ('denied',_("Denied")),
    ]

    status = models.CharField(
        max_length=12, 
        choices=STATUS_CHOICES, 
        default='new'
    )

    notes = models.TextField(
        blank=True,
        help_text="Enter any notes for this case",
        default=''
    )

    def __str__(self):
        return f'{self.id} - {self.last_name} at {self.street_address}'

    @property
    def discount_amount(self):
        very_low_income_thresholds = helpers.get_lower_income_thresholds()
        max_income = very_low_income_thresholds[self.household_size]
        return 90 if self.annual_income <= max_income else 60

    class Meta:
        verbose_name = 'Discount Application'
        verbose_name_plural = 'Discount Applications'

class EmailCommunication(models.Model):
    email_address = models.EmailField(primary_key=True, blank=False, null=False)
    discount_application_received = models.BooleanField(default=False)
    amnesty_application_received = models.BooleanField(default=False)
    enrolled_in_amnesty_program = models.BooleanField(default=False)
    enrolled_in_discount_program = models.BooleanField(default=False)

    # Metadata
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.email_address}'


@deconstructible
class FileValidator():
    """A class to validate a file with size and contents constraints

    Attributes
    ----------
    error_messages : dict
        dictionary with error messages for each constructor parameter

    Source: # https://stackoverflow.com/questions/20272579/django-validate-file-type-of-uploaded-file
    """
    error_messages = {
     'max_size': _("Ensure this file size is not greater than %(max_size)s."
                  " Your file size is %(size)s."),
     'min_size': _("Ensure this file size is not less than %(min_size)s. "
                  "Your file size is %(size)s."),
     'content_type': _("Files of type %(content_type)s are not supported."),
    }

    def __init__(self, max_size=None, min_size=None, content_types=()):
        """
        Parameters
        ----------
        max_size : int
            optional maximum number of bytes
        min_size : int
            optional minimum number of bytes
        content_type : tuple
            tuple of content types in MIME form such as ('image/jpeg', 'application/pdf', )

        """
        self.max_size = max_size
        self.min_size = min_size
        self.content_types = content_types

    def __call__(self, data):
        if self.max_size is not None and data.size > self.max_size:
            params = {
                'max_size': filesizeformat(self.max_size), 
                'size': filesizeformat(data.size),
            }
            raise ValidationError(self.error_messages['max_size'],
                                   code='max_size', params=params)

        if self.min_size is not None and data.size < self.min_size:
            params = {
                'min_size': filesizeformat(self.min_size),
                'size': filesizeformat(data.size)
            }
            raise ValidationError(self.error_messages['min_size'], 
                                   code='min_size', params=params)

        if self.content_types:
            content_type = magic.from_buffer(data.read(), mime=True)
            data.seek(0)

            if content_type not in self.content_types:
                params = { 'content_type': content_type }
                raise ValidationError(self.error_messages['content_type'],
                                   code='content_type', params=params)

    def __eq__(self, other):
        return (
            isinstance(other, FileValidator) and
            self.max_size == other.max_size and
            self.min_size == other.min_size and
            self.content_types == other.content_types
        )


def path_and_rename(instance, filename):
    """Renames and paths document file on upload

    The filename is based on the primary key of the document object.
    If the primary key does not exist, the filename is the current datetime.

    When this function is called, the document's content type 
    has already gone through 2 checks

        1) File extension is validated against accepted extensions (.jpeg, .png, etc)
        2) FileValidator checks the content of the file's header 
            (malicious code might be masked with an accepted extension)

    Parameters
    ----------
    instance : Document instance
        instance of Document object
    filename : str
        string of uploaded file
    
    Returns
    -------
    str
        Constructed path and name for file to upload to S3

    """
    upload_to = 'documents'
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = f'{instance.pk}'
    else:
        t = datetime.now()
        filename = f'{t.year}-{t.month}-{t.day}-{t.hour}-{t.minute}-{t.second}-{t.microsecond}'
    return f'{upload_to}/{filename}.{ext}'


# Validator for acceptable file uploads, used by both Document model and in forms.py
ACCEPTED_FILE_VALIDATOR = FileValidator(
    max_size=1024 * 4000, content_types=(
        'image/jpeg',
        'image/png',
        'application/pdf',
        'image/tiff',
        )
    )

class Document(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    doc_type = models.CharField(max_length=9, choices=[
        ('income', _('Income')),
        ('benefits', _('Benefits')),
        ('residence', _('Residence'))
    ])
    doc_file = models.FileField(upload_to=path_and_rename, blank=True, validators=[ACCEPTED_FILE_VALIDATOR])
    
    # Metadata
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.application.id} - {self.application.last_name} at {self.application.street_address} - {self.doc_type}'

class ForgivenessApplication(models.Model):
    # Metadata
    history = HistoricalRecords()

    # ResidentInfoForm
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    middle_initial = models.CharField(
        max_length=5, 
        blank=True
    )

    # AddressForm

pathways/templates/pathways/docs/later-docs.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card">

    <form style="display: inline-block;" method="POST">
        {% csrf_token %}
        <header class="form-card__header">
            <h1 class="form-card__title">{{ card_title }}</h1>
        </header>
        <div class="form-card__content">
            {% include 'pathways/snippets/already-submit-reveal.html' %}
            {% for field in form.visible_fields %}
            <div class="form-group {% if field.errors %}form-group--error{% endif %}">
                <label for="{{field.name}}" class="form-question">{{ field.label }}</label>
                <p class="text--help nudge--tiny">{{ field.help_text }}</p>
                <input type="text" class="text-input form-width--name" id="{{field.name}}"
                    placeholder="{{ field.placeholder }}" name="{{field.name}}">
                {% if field.errors %}
                {% for error in field.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>
            {% endfor %}
        </div>

        <div class="form-card__footer">
            <button name="button" type="submit" class="button button--primary">
                <i class=&quot;button__icon icon-arrow_forward&quot; aria-hidden='true'>
                </i>{% trans "Continue" %}<i class="button__icon icon-arrow_forward" aria-hidden='true'></i>
            </button>
        </div>
    </form>
</div>
{% endblock question %}

pathways/templates/pathways/docs/more-doc-info.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card">

    <form style="display: inline-block;" method="POST">
        {% csrf_token %}
        <header class="form-card__header">
            <h1 class="form-card__title">{{ card_title }}</h1>
        </header>
        <div class="form-card__content">
            <div class="form-group {% if form.household_size.errors %}form-group--error{% endif %}">
                <label class="form-question" for="id_household_size">
                    <p class="form-question">{{ form.household_size.label_tag }}</p>
                </label>
                <div class="select">
                    <select class="select__element" name="household_size" id="id_household_size">
                        <option selected disabled>{% trans "Select household size" %}</option>
                        {% for value, text in form.household_size.field.choices %}
                        <option value="{{ value }}">{{ text }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% if form.household_size.errors %}
                {% for error in form.household_size.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group {% if form.rent_or_own.errors %}form-group--error{% endif %}">
                <label class="form-question" for="id_rent_or_own">{{ form.rent_or_own.label }}</label>
                <p class="text--help">{{ form.rent_or_own.help_text }}</p>
                <radiogroup class="input-group--inline">
                    {% for value, text in form.rent_or_own.field.choices %}
                    <label for="id_rent_or_own_{{ value }}" class="radio-button">
                        <input type="radio" name="rent_or_own" id="id_rent_or_own_{{ value }}"
                            value="{{ value }}">{{ text }}
                    </label>
                    {% endfor %}
                </radiogroup>
                {% if form.rent_or_own.errors %}
                {% for error in form.rent_or_own.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group {% if form.street_address.errors %}form-group--error{% endif %}">
                <label for="street_address" class="form-question">{{ form.street_address.label }}</label>
                <input type="text" class="text-input form-width--name" id="street_address"
                    placeholder="123 Main St" name="street_address">
                {% if form.street_address.errors %}
                {% for error in form.street_address.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group {% if form.apartment_unit.errors %}form-group--error{% endif %}">
                <label for="apartment_unit" class="form-question">{{ form.apartment_unit.label }}</label>
                <input type="text" class="text-input form-width--name" id="apartment_unit"
                    placeholder="{{ form.apartment_unit.placeholder }}" name="apartment_unit">
                {% if form.apartment_unit.errors %}
                {% for error in form.apartment_unit.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>
            
        </div>

        <div class="form-card__footer">
            <button name="button" type="submit" class="button button--primary" data-disable-with=<i
                class=&quot;button__icon icon-arrow_forward&quot; aria-hidden='true'></i> Continue
                <i class="button__icon icon-arrow_forward" aria-hidden='true'></i>
            </button>
        </div>

    </form>
</div>
{% endblock question %}

pathways/templates/pathways/docs/no-doc-found.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card form-card--transition">
    <div class="form-card__header">
        <h1 class="form-card__title">
            {% trans "We couldn't match the info you provided to any existing application." %}
        </h1>
    </div>
    <div class="form-card__content">
        <p>
            {% blocktrans trimmed %}
            Although we couldn't find an existing application with the information you provided, submitting a new
            application <b>only takes about 5 minutes</b>.
            {% endblocktrans %}
        </p>
        {% include 'pathways/snippets/already-submit-reveal.html' %}
    </div>
    <div class="form-card__footer">
        <a class="button button--primary" href="{% url 'pathways-apply-discount-overview' %}">
            {% trans "Start new application" %}</a>
        <a class="button" href="{% url 'pathways-later-documents' %}">
            {% trans "Change my answers" %} <i class="icon icon-replay"></i></a>
    </div>
</div>
{% endblock question %}

pathways/templates/pathways/docs/overview.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card form-card--transition">
    <div class="grid">
        <div class="grid__item width-two-thirds shift-one-sixth">
            <h1 class="form-card__title">
                {% trans "Remember your application cannot be approved until you submit proof." %}</h1>
            <div class="notice">
                <i class="fas fa-camera fa-3x spacing-below-35 text--blue-dark"></i>
                <p class="text--blue-dark">You can <b>upload photos</b> of these documents from a smartphone or computer.</p>
            </div>
            <p>{% trans "Based on your answers you will need:" %}</p>
            <div class="vertical-steps">

                {% if has_household_benefits %}
                <div class="vertical-steps__step">
                    <i class="fas fa-clipboard-list fa-3x spacing-below-35 text--blue-dark"></i>
                    <div class="vertical-steps__title">{% trans "Proof from other benefit programs" %}</div>
                    <p>
                        {% trans "Any documents that prove a member of your household is currently enrolled in one of the following programs:" %}
                        <ul class="list--bulleted text--left">
                            <li>{% trans "Supplemental Nutrition Assistance Program (SNAP/Food Stamps)" %}</li>
                            <li>{% trans "Home Energy Assistance Program (HEAP)" %}</li>
                            <li>{% trans "Supplemental Security Income (SSI)" %}</li>
                            <li>{% trans "Public Assistance" %}</li>
                        </ul>
                    </p>
                </div>
                {% else %}
                <div class="vertical-steps__step">
                    <i class="fas fa-money-check-alt fa-3x spacing-below-35 text--blue-dark"></i>
                    <div class="vertical-steps__title">{% trans "A paystub from the last 30 days" %}</div>
                    <p>{% trans "This is for any income you get from a job. If you are paid in cash, you can submit a letter from your employer." %}</p>
                </div>
                {% endif %}

                <div class="vertical-steps__step">
                    <i class="fas fa-home fa-3x spacing-below-35 text--blue-dark"></i>
                    <div class="vertical-steps__title">
                        {% if rent_or_own == 'own' %}
                        {% trans "Proof of home ownership" %}
                        {% else %}
                        {% trans "Proof of tenant status" %}
                        {% endif %}
                    </div>
                    <p>
                        {% if rent_or_own == 'own' %}
                        {% trans "This could be a deed, tax document, or any official document that indicates you own your home." %}
                        {% else %}
                        {% trans "This can be a photo of your lease, a rent receipt, or a landlord statement indicating who is responsible for paying the water bill." %}
                        {% endif %}
                    </p>
                </div>

            </div>

            <p><a class="button button--primary" href="{% url 'pathways-apply-documents-income' %}">
                    {% trans "Continue" %}<i class="button__icon icon-arrow_forward" aria-hidden='true'></i></a></p>
            </button>
        </div>
    </div>
</div>
{% endblock question %}