affordable_water/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from two_factor.urls import urlpatterns as tf_urls

from .admin import AdminSiteOTPRequiredMixinRedirSetup

admin.site.__class__ = AdminSiteOTPRequiredMixinRedirSetup

handler404 = 'pathways.views.handler404'
handler500 = 'pathways.views.handler500'

urlpatterns = [path('i18n/', include('django.conf.urls.i18n'), name='set_language'),]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('', include('pathways.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='pathways/password_reset.html'), 
        name='password_reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='pathways/password_reset_done.html'), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='pathways/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='pathways/password_reset_complete.html'), 
        name='password_reset_complete'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pathways/urls.py
from django.urls import path

from pathways import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='pathways-home'),
    path('about/', views.AboutView.as_view(),name='pathways-about'),
    path('nondiscrimination/', views.NondiscriminationView.as_view(), name='pathways-nondiscrimination'),
    path('privacy/', views.PrivacyView.as_view(), name='pathways-privacy'),
    path('metrics/', views.ProgramMetricsView.as_view(), name='pathways-metrics'),
    path('apply/', views.ApplyOverviewAssistanceView.as_view(),
        name='pathways-apply'),
    path('apply/discount-overview/', views.ApplyDiscountView.as_view(),
        name='pathways-apply-discount-overview'),
    # Amnesty Debt Forgiveness
    path('forgive/overview/', views.ForgiveOverviewView.as_view(),
        name='pathways-forgive-overview'),
    path('forgive/city-resident/', views.ForgiveCityResidentView.as_view(),
        name='pathways-forgive-city-resident'),
    path('forgive/additional-questions/', views.ForgiveAdditionalQuestionsView.as_view(),
        name='pathways-forgive-additional-questions'),
    path('forgive/resident-info/', views.ForgiveResidentInfoView.as_view(),
        name='pathways-forgive-resident-info'),
    path('forgive/refer/', views.ForgiveReferralView.as_view(),
        name='pathways-forgive-refer'),
    path('forgive/review-application/', views.ForgiveReviewApplicationView.as_view(),
        name='pathways-forgive-review-application'),
    path('forgive/confirmation/', views.ForgiveConfirmationView.as_view(),
        name='pathways-forgive-confirmation'),
    path('apply/city-resident/', views.CityResidentView.as_view(),
        name='pathways-apply-city-resident'),    
    path('apply/non-resident/', views.NonResidentView.as_view(),
        name='pathways-apply-non-resident'),
    # Household
    path('apply/household-size/', views.HouseholdSizeView.as_view(),
        name='pathways-apply-household-size'),
    path('apply/household-benefits/', views.HouseholdBenefitsView.as_view(),
        name='pathways-apply-household-benefits'),
    # Income
    path('apply/household-contributors/', views.HouseholdContributorsView.as_view(),
        name='pathways-apply-household-contributors'),
    path('apply/job-status/', views.JobStatusView.as_view(),
        name='pathways-apply-job-status'),
    path('apply/self-employment/', views.SelfEmploymentView.as_view(),
        name='pathways-apply-self-employment'),
    path('apply/number-of-jobs/', views.NumberOfJobsView.as_view(),
        name='pathways-apply-number-of-jobs'),
    path('apply/income-methods/', views.IncomeMethodsView.as_view(),
        name='pathways-apply-income-methods'),
    path('apply/income/', views.IncomeView.as_view(),
        name='pathways-apply-income'),
    path('apply/other-income-sources/', views.OtherIncomeSourcesView.as_view(),
        name='pathways-apply-other-income-sources'),
    path('apply/non-job-income/', views.NonJobIncomeView.as_view(),
        name='pathways-apply-non-job-income'),
    # Eligibility
    path('apply/review-eligibility/', views.ReviewEligibilityView.as_view(),
        name='pathways-apply-review-eligibility'),
    path('apply/eligibility/', views.EligibilityView.as_view(),
        name='pathways-apply-eligibility'),
    # Additional Info
    path('apply/additional-questions/', views.AdditionalQuestionsView.as_view(),
        name='pathways-apply-additional-questions'),
    path('apply/resident-info/', views.ResidentInfoView.as_view(),
        name='pathways-apply-resident-info'),
    path('apply/account-holder/', views.AccountHolderView.as_view(),
        name='pathways-apply-account-holder'),
    path('apply/address/', views.AddressView.as_view(),
        name='pathways-apply-address'),
    path('apply/contact-info/', views.ContactInfoView.as_view(),
        name='pathways-apply-contact-info'),
    path('apply/account-number/', views.AccountNumberView.as_view(),
        name='pathways-apply-account-number'),
    # Review and sign
    path('apply/review-application/', views.ReviewApplicationView.as_view(),
        name='pathways-apply-review-application'),
    path('apply/legal/', views.LegalView.as_view(),
        name='pathways-apply-legal'),
    path('apply/refer/', views.ReferralView.as_view(),
        name='pathways-apply-refer'),
    path('apply/signature/', views.SignatureView.as_view(),
        name='pathways-apply-signature'),
    # Documents
    path('apply/documents-overview/', views.DocumentOverviewView.as_view(),
        name='pathways-apply-documents-overview'),
    path('apply/documents-income/', views.DocumentIncomeView.as_view(),
        name='pathways-apply-documents-income'),
    path('apply/documents-residence/', views.DocumentResidenceView.as_view(),
        name='pathways-apply-documents-residence'),
    path('apply/confirmation/', views.ConfirmationView.as_view(),
        name='pathways-apply-confirmation'),
    path('later-documents/', views.LaterDocumentsView.as_view(),
        name='pathways-later-documents'),
    path('later-documents/no-match-found/', views.NoDocumentFoundView.as_view(),
        name='pathways-later-documents-not-found'),
    path('later-documents/more-info-needed/', views.MoreDocumentInfoRequiredView.as_view(),
        name='pathways-later-documents-more-info')
]

pathways/models.py
from django.db import models
from django.core.validators import RegexValidator, ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils.deconstruct import deconstructible
from django.template.defaultfilters import filesizeformat
from datetime import datetime
from simple_history.models import HistoricalRecords
import magic

from pathways import helpers

class Application(models.Model):
    # Metadata
    history = HistoricalRecords()

    HOUSEHOLD_SIZE_CHOICES = [
        (1,_('Just me')),
        (2,_('2 people')),
        (3,_('3 people')),
        (4,_('4 people')),
        (5,_('5 people')),
        (6,_('6 people')),
        (7,_('7 people')),
        (8,_('8 people')),
    ]
    # HouseholdForm
    household_size = models.IntegerField(
        choices=HOUSEHOLD_SIZE_CHOICES,
        help_text=_("Typically how many people you regularly share living expenses with, including yourself. "
                    "If you live with them, include children under 21, spouses/partners, and parents.")
    )
    # AutoEligibleForm
    has_household_benefits = models.BooleanField()

    # Data from Income forms will be in a seperate model because 
    # if has_household_benefits is True, user won't have to enter income data
    annual_income = models.DecimalField(
        max_digits=11,
        decimal_places=2,
        blank=True,
        default=0,
        help_text=_("Must specify annual income if applicant does not have other household benefits (HEAP, SNAP, etc.)")
    )

    # ResidentInfoForm
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    middle_initial = models.CharField(max_length=5, blank=True)
    rent_or_own = models.CharField(
        max_length=4, 
        choices=(
            ('rent',_("Rent")),
            ('own',_("Own")))
    )

    # AddressForm
    street_address = models.CharField(
        max_length=200,
        validators=[RegexValidator(
            regex=r'^\d+ .*',
            message=_("Make sure to enter a street number before the street name, for example 123 Main St"))
        ]
    )
    apartment_unit = models.CharField(
        max_length=10,
        blank=True,
        help_text=_("Skip this if you don't live in an apartment")
    )
    zip_code = models.CharField(
        max_length=5,
        validators=[RegexValidator(
            regex=r'^\d{5}$',
            message=_("Your ZIP code must be exactly 5 digits"))
        ]
    )

    # ContactInfoForm
    phone_number = models.CharField(
        max_length=12, 
        validators=[RegexValidator(
            regex=r'^(\d{10}|(\d{3}\-\d{3}\-\d{4}))|(\(\d{3}\)\s?\d{3}\-\d{4})',
            message=_("Please use a valid phone number format such as 716-555-5555."))
            ]
    )
    email_address = models.EmailField(
        blank=True, 
        help_text=_("Optional to provide for status updates on your application")
    )

    # account_holder in ResidentInfoForm
    account_holder = models.CharField(max_length=8, choices=[
        ('me',_("Me")),
        ('landlord',_("My landlord")),
        ('other',_("Another person")),
    ])

    # AccountHolderForm
    account_first = models.CharField(max_length=100)
    account_last = models.CharField(max_length=100)
    account_middle = models.CharField(max_length=5, blank=True)

    # AccountNumberForm
    account_number = models.CharField(
        max_length=30,
        blank=True,
        validators=[RegexValidator(
            regex=r'^\d+$',
            message=_("Please enter only digits"))
        ]
    )

    # LegalForm
    legal_agreement = models.BooleanField()

    # SignatureForm
    signature = models.CharField(max_length=250)

    STATUS_CHOICES = [
        ('new',_("New")),
        ('in_progress', _("In Progress")),
        ('enrolled',_("Enrolled")),
        ('denied',_("Denied")),
    ]

    status = models.CharField(
        max_length=12, 
        choices=STATUS_CHOICES, 
        default='new'
    )

    notes = models.TextField(
        blank=True,
        help_text="Enter any notes for this case",
        default=''
    )

    def __str__(self):
        return f'{self.id} - {self.last_name} at {self.street_address}'

    @property
    def discount_amount(self):
        very_low_income_thresholds = helpers.get_lower_income_thresholds()
        max_income = very_low_income_thresholds[self.household_size]
        return 90 if self.annual_income <= max_income else 60

    class Meta:
        verbose_name = 'Discount Application'
        verbose_name_plural = 'Discount Applications'

class EmailCommunication(models.Model):
    email_address = models.EmailField(primary_key=True, blank=False, null=False)
    discount_application_received = models.BooleanField(default=False)
    amnesty_application_received = models.BooleanField(default=False)
    enrolled_in_amnesty_program = models.BooleanField(default=False)
    enrolled_in_discount_program = models.BooleanField(default=False)

    # Metadata
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.email_address}'


@deconstructible
class FileValidator():
    """A class to validate a file with size and contents constraints

    Attributes
    ----------
    error_messages : dict
        dictionary with error messages for each constructor parameter

    Source: # https://stackoverflow.com/questions/20272579/django-validate-file-type-of-uploaded-file
    """
    error_messages = {
     'max_size': _("Ensure this file size is not greater than %(max_size)s."
                  " Your file size is %(size)s."),
     'min_size': _("Ensure this file size is not less than %(min_size)s. "
                  "Your file size is %(size)s."),
     'content_type': _("Files of type %(content_type)s are not supported."),
    }

    def __init__(self, max_size=None, min_size=None, content_types=()):
        """
        Parameters
        ----------
        max_size : int
            optional maximum number of bytes
        min_size : int
            optional minimum number of bytes
        content_type : tuple
            tuple of content types in MIME form such as ('image/jpeg', 'application/pdf', )

        """
        self.max_size = max_size
        self.min_size = min_size
        self.content_types = content_types

    def __call__(self, data):
        if self.max_size is not None and data.size > self.max_size:
            params = {
                'max_size': filesizeformat(self.max_size), 
                'size': filesizeformat(data.size),
            }
            raise ValidationError(self.error_messages['max_size'],
                                   code='max_size', params=params)

        if self.min_size is not None and data.size < self.min_size:
            params = {
                'min_size': filesizeformat(self.min_size),
                'size': filesizeformat(data.size)
            }
            raise ValidationError(self.error_messages['min_size'], 
                                   code='min_size', params=params)

        if self.content_types:
            content_type = magic.from_buffer(data.read(), mime=True)
            data.seek(0)

            if content_type not in self.content_types:
                params = { 'content_type': content_type }
                raise ValidationError(self.error_messages['content_type'],
                                   code='content_type', params=params)

    def __eq__(self, other):
        return (
            isinstance(other, FileValidator) and
            self.max_size == other.max_size and
            self.min_size == other.min_size and
            self.content_types == other.content_types
        )


def path_and_rename(instance, filename):
    """Renames and paths document file on upload

    The filename is based on the primary key of the document object.
    If the primary key does not exist, the filename is the current datetime.

    When this function is called, the document's content type 
    has already gone through 2 checks

        1) File extension is validated against accepted extensions (.jpeg, .png, etc)
        2) FileValidator checks the content of the file's header 
            (malicious code might be masked with an accepted extension)

    Parameters
    ----------
    instance : Document instance
        instance of Document object
    filename : str
        string of uploaded file
    
    Returns
    -------
    str
        Constructed path and name for file to upload to S3

    """
    upload_to = 'documents'
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = f'{instance.pk}'
    else:
        t = datetime.now()
        filename = f'{t.year}-{t.month}-{t.day}-{t.hour}-{t.minute}-{t.second}-{t.microsecond}'
    return f'{upload_to}/{filename}.{ext}'


# Validator for acceptable file uploads, used by both Document model and in forms.py
ACCEPTED_FILE_VALIDATOR = FileValidator(
    max_size=1024 * 4000, content_types=(
        'image/jpeg',
        'image/png',
        'application/pdf',
        'image/tiff',
        )
    )

class Document(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    doc_type = models.CharField(max_length=9, choices=[
        ('income', _('Income')),
        ('benefits', _('Benefits')),
        ('residence', _('Residence'))
    ])
    doc_file = models.FileField(upload_to=path_and_rename, blank=True, validators=[ACCEPTED_FILE_VALIDATOR])
    
    # Metadata
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.application.id} - {self.application.last_name} at {self.application.street_address} - {self.doc_type}'

class ForgivenessApplication(models.Model):
    # Metadata
    history = HistoricalRecords()

    # ResidentInfoForm
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    middle_initial = models.CharField(
        max_length=5, 
        blank=True
    )

    # AddressForm

pathways/templates/pathways/apply/city-resident.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card form-card--transition">
    <div class="form-card__header">
        <img src="{% static 'pathways/email-assets/Seal_of_Buffalo_New_York.png' %}" alt="Seal of the City of Buffalo">
        <h1 id="city_resident-yes-no-buttons" class="form-card__title">
            {{ form.city_resident.label }}
        </h1>
        <p>{{ form.city_resident.help_text }}</p>
        <div class="reveal is-hidden">
            <p><a href="#" class="reveal__link">{% trans "Check map" %}</a></p>
            <div class="reveal__content text--left">
                <p>
                    {% blocktrans trimmed %}
                    If you are not a <b>City of Buffalo</b> resident, you are not serviced by Buffalo Water and are <b>not eligible</b> for this program. You are likely served by the <a href="https://www.ecwa.org/">Erie County Water Authority</a>.
                    {% endblocktrans %}
                </p>
                <img src="{% static 'pathways/cfa-styleguide-gem/app/assets/images/buffalo_city_limits.png' %}" alt="Map of the official City of Buffalo boundary">
            </div>
        </div>
    </div>

    <form method="POST" style="display: inline-block;">
        {% csrf_token %}
        <label class="sr-only" for="id_city_resident">{{ form.city_resident.label }}</label>
        <p class="sr-only text--help">{{ form.city_resident.help_text }}</p>
        
        <button type="submit" name="city_resident" class="button" value="True"
            aria-describedby="city_resident-yes-no-buttons">
            <span class="button__icon--left emoji emoji--inline emoji--checkmark"></span></i>{% trans "Yes" %}</button>
        <button type="submit" name="city_resident" class="button" value="False"
            aria-describedby="city_resident-yes-no-buttons">
            <span class="button__icon--left emoji emoji--inline emoji--crossmark"></span>{% trans "No" %}</button>
    </form>
</div>
{% endblock question %}

pathways/templates/pathways/apply/discount-overview.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card form-card--transition">
    <div class="form-card__header">
        <h1 class="form-card__title">{% trans "Here's how the Affordable Water Discount Program works." %}</h1>
    </div>
    <div class="form-card__content">
        <div class="vertical-steps spacing-below-10">
            <div class="vertical-steps__step">
                <i class="fas fa-clipboard-list fa-2x spacing-above-10 spacing-below-10 text--blue-light"></i>
                <p class="with-no-padding"><b>{% trans "Submit an application" %}</b></p>
                <p>
                    {% trans "We’ll guide you step by step. This should take about 10 minutes." %}</p>
            </div>
            <div class="vertical-steps__step">
                <i class="fas fa-file-upload fa-2x spacing-above-10 spacing-below-10 text--blue-light"></i>
                <p class="with-no-padding"><b>{% trans "Submit proof of your situation" %}</b></p>
                <p>
                    {% trans "This includes documents like your paystubs. You can do this during your application or come back to this website any time in the next 30 days." %}
                </p>

                <div class="reveal is-hidden">
                    <p><a href="#" class="reveal__link">{% trans "What proof to submit" %}</a></p>
                    <div class="reveal__content text--left">

                        <p class="text--small">
                            {% trans "We’ll let you know what to submit at the end of the application based on the answers you gave us." %}
                        </p>

                        <p class="heading-25-small">
                            {% trans "These documents are usually required to get the water discount:" %}</p>
                        <ul class="list--bulleted text--small">
                            <li>{% trans "Proof of any income." %}</li>
                            <li>{% trans "Proof of City of Buffalo homeownership <strong><u>or</u></strong> copy of rental lease." %}
                            </li>
                        </ul>

                        <p class="heading-25-small">
                            {% trans "Any proof of the following will automatically approve your application:" %}</p>
                        <ul class="list--bulleted text--small">
                            <li>{% trans "Supplemental Nutrition Assistance Program (SNAP)" %}</li>
                            <li>{% trans "Home Energy Assistance Program (HEAP)" %}</li>
                            <li>{% trans "Supplemental Security Income (SSI)" %}</li>
                            <li>{% trans "Public Assistance (PA)" %}</li>
                        </ul>

                        <p class="heading-25-small">
                            {% trans "These documents are optional but can increase your benefit amount:" %}</p>
                        <ul class="list--bulleted text--small">
                            <li>{% trans "If you are 65+ or disabled, a copy of enhanced STAR tax exemption." %}</li>
                        </ul>

                        <p class="heading-25-small">
                            {% trans "What if I can’t get the proof right now?" %}
                        </p>
                        <p class="text--small">
                            {% trans "You can still apply now and submit documents any time in the next 30 days." %}
                        </p>
                    </div>
                </div>
            </div>
            <div class="vertical-steps__step">
                <i class="fas fa-faucet fa-2x spacing-above-10 spacing-below-10 text--blue-light"></i>
                <p class="with-no-padding"><b>{% trans "Get discount on your next water bill" %}</b></p>
                <p>
                    {% trans "If you’re approved, you’ll receive a discount on your next water bill." %}</p>

            </div>
        </div>
        {% include "pathways/snippets/covid-19.html" %}

    </div>
    <div class="form-card__footer">
        <p>
            <a class="button button--primary" href="{% url 'pathways-apply-city-resident' %}">
                {% trans "Get started" %} <i class="icon icon-arrow_forward"></i>
            </a> </p>
    </div>
</div>
{% endblock question %}

pathways/templates/pathways/apply/household-benefits.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card form-card--transition">
    <div class="form-card__header">
        <i class="fas fa-clipboard-list fa-3x spacing-below-35 text--blue-dark"></i>
        <h1 id="household-benefits-yes-no-buttons" class="form-card__title">
            {{ form.has_household_benefits.label }}
        </h1>
        <ul class="list--bulleted text--left">
            <li>{% trans "Supplemental Nutrition Assistance Program (SNAP/Food Stamps)" %}</li>
            <li>{% trans "Home Energy Assistance Program (HEAP)" %}</li>
            <li>{% trans "Supplemental Security Income (SSI)" %}</li>
            <li>{% trans "Public Assistance" %}</li>
        </ul>
    </div>

    <form method="POST" style="display: inline-block;">
        {% csrf_token %}
        <label class="sr-only" for="id_has_household_benefits">{{ form.has_household_benefits.label }}</label>
        <p class="sr-only text--help">{{ form.has_household_benefits.help_text }}</p>
        <button type="submit" name="has_household_benefits" class="button" value="True"
            aria-describedby="household-benefits-yes-no-buttons">
            <span class="button__icon--left emoji emoji--inline emoji--checkmark"></span></i>{% trans "Yes" %}</button>
        <button type="submit" name="has_household_benefits" class="button" value="False"
            aria-describedby="household-benefits-yes-no-buttons">
            <span class="button__icon--left emoji emoji--inline emoji--crossmark"></span>{% trans "No" %}</button>
    </form>
</div>
{% endblock question %}

pathways/templates/pathways/apply/number-of-jobs.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card form-card--transition">
    <form method="POST">
        {% csrf_token %}
        
        <div class="form-card__content">
            <div class="form-card__header">
                <h1 class="form-card__title">{{ form.number_of_jobs.label }}</h1>
                <p>{{ form.number_of_jobs.help_text }}</p>
            </div>

            <div class="form-group {% if form.number_of_jobs.errors %}form-group--error{% endif %}">
                <label class="sr-only" for="id_number_of_jobs">{{ form.number_of_jobs.label }}</label>
                <p class="sr-only text--help">{{ form.number_of_jobs.help_text }}</p>
                <div class="select">
                    <select class="select__element" name="number_of_jobs" id="id_number_of_jobs">
                        {% for value, text in form.number_of_jobs.field.choices %}
                        <option value="{{ value }}">{{ text }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% if form.number_of_jobs.errors %}
                    {% for error in form.number_of_jobs.errors %}
                        <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="form-card__footer">
                <button name="button" type="submit" class="button button--primary" data-disable-with=<i
                    class=&quot;button__icon icon-arrow_forward&quot; aria-hidden='true'></i> Continue
                    <i class="button__icon icon-arrow_forward" aria-hidden='true'></i>
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock question %}

pathways/templates/pathways/apply/resident-info.html
{% extends "pathways/snippets/question.html" %}
{% load i18n %}
{% load static %}

{% block question %}
<div class="form-card">

    <form style="display: inline-block;" method="POST">
        {% csrf_token %}
        <header class="form-card__header">
            <h1 class="form-card__title">{% trans "Let’s get some basic information." %}</h1>
        </header>
        <div class="form-card__content">
            <div class="form-group {% if form.first_name.errors %}form-group--error{% endif %}">
                <label for="first_name" class="form-question">{{ form.first_name.label }}</label>
                <input type="text" class="text-input form-width--name" id="first_name"
                    placeholder="{{ form.first_name.placeholder }}" name="first_name">
                {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group {% if form.last_name.errors %}form-group--error{% endif %}">
                <label for="last_name" class="form-question">{{ form.last_name.label }}</label>
                <input type="text" class="text-input form-width--name" id="last_name"
                    placeholder="{{ form.last_name.placeholder }}" name="last_name">
                {% if form.last_name.errors %}
                {% for error in form.last_name.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group {% if form.middle_initial.errors %}form-group--error{% endif %}">
                <label for="middle_initial" class="form-question">{{ form.middle_initial.label }}</label>
                <input type="text" class="text-input form-width--name" id="middle_initial"
                    placeholder="{{ form.middle_initial.placeholder }}" name="middle_initial">
                {% if form.middle_initial.errors %}
                {% for error in form.middle_initial.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group {% if form.rent_or_own.errors %}form-group--error{% endif %}">
                <label class="form-question" for="id_rent_or_own">{{ form.rent_or_own.label }}</label>
                <p class="text--help">{{ form.rent_or_own.help_text }}</p>
                <radiogroup class="input-group--inline">
                    {% for value, text in form.rent_or_own.field.choices %}
                    <label for="id_rent_or_own_{{ value }}" class="radio-button">
                        <input type="radio" name="rent_or_own" id="id_rent_or_own_{{ value }}"
                            value="{{ value }}">{{ text }}
                    </label>
                    {% endfor %}
                </radiogroup>
                {% if form.rent_or_own.errors %}
                {% for error in form.rent_or_own.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>

            <div class="form-group {% if form.account_holder.errors %}form-group--error{% endif %}">
                <label class="form-question" for="id_account_holder">
                    <p class="form-question">{{ form.account_holder.label_tag }}</p>
                </label>
                <div class="select">
                    <select class="select__element" name="account_holder" id="id_account_holder">
                        <option selected disabled>{% trans "Select bill payer" %}</option>
                        {% for value, text in form.account_holder.field.choices %}
                        <option value="{{ value }}">{{ text }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% if form.account_holder.errors %}
                {% for error in form.account_holder.errors %}
                <p class="text--error"><i class="icon-warning"></i>{{ error|escape }}</p>
                {% endfor %}
                {% endif %}
            </div>
        </div>


        <div class="form-card__footer">
            <button name="button" type="submit" class="button button--primary" data-disable-with=<i
                class=&quot;button__icon icon-arrow_forward&quot; aria-hidden='true'></i> Continue
                <i class="button__icon icon-arrow_forward" aria-hidden='true'></i>
            </button>
        </div>
    </form>
</div>
{% endblock question %}